version: '3.8'

services:
  # O Banco de dados que o Celery usa (Redis)
  redis:
    image: redis:alpine
    container_name: enel_redis

  # O Coração do sistema (Django)
  web:
    build: .
    container_name: enel_oficios
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./media:/app/media  # Mapeia a pasta media para o Windows
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis

  # O Robô que executa as tarefas (Celery Worker)
  worker:
    build: .
    container_name: enel_worker
    command: celery -A core worker -l info
    volumes:
      - .:/app
      - ./media:/app/media  # Garante que o robô salve na pasta certa
    env_file:
      - .env
    depends_on:
      - redis
      - web

  # O Relógio que agenda as tarefas (Celery Beat)
  beat:
    build: .
    container_name: enel_beat
    command: celery -A core beat -l info
    volumes:
      - .:/app
      - ./media:/app/media  # Permite que o agendador veja os arquivos se necessário
    env_file:
      - .env
    depends_on:
      - redis
      - web